library/books/urls.py
from django.urls import include, path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('author/<int:author_id>/', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book'),
    path('my_books/', views.LoanedBooksByUser.as_view(), name='my_books'),
]

library/library/urls.py
from django.contrib.auth import urls
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_profile/', include('user_profile.urls')),
    path('library/', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='library/', permanent=True)),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

library/books/models.py
from django.db import models
from django.contrib.auth.models import User 
import uuid
from django.utils.translation import gettext_lazy as _
from datetime import date
from tinymce.models import HTMLField


# Create your models here.
class Genre(models.Model):
    name = models.CharField(_('pavadinimas'), max_length=200, help_text=_('iveskite knygos zanra (pvz. detektyvas)'))

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(_('vardas'), max_length=100)
    last_name = models.CharField(_('pavarde'), max_length=100)
    description = HTMLField(_('apie autoriu'), blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_books_count(self):
        return self.books.count()
    get_books_count.short_description = _('knygos')

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = _('autorius')
        verbose_name_plural = _('autoriai')


class Book(models.Model):
    title = models.CharField(_('pavadinimas'), max_length=250)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='books', verbose_name=_('autorius'))
    summary = HTMLField(_('santrauka'), help_text=_('trumpas knygos parasymas'))
    isbn = models.CharField('ISBN', max_length=13, help_text=_('13 Simbolių')+'<a href="https://www.isbn-international.org/content/what-isbn" target="_blank">ISBN'+ _('kodas')+'</a>')
    genre = models.ManyToManyField(Genre, verbose_name=_("zanras"), help_text=_("isrinkite zanrus siai knygai"))
    cover = models.ImageField(_('viršelis'), upload_to='books/covers', null=True, blank=True)

    def __str__(self):
        return f'{str(self.author)} - {self.title}'

    def display_genres(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genres.short_description = _('zanrai')

    def get_available_instances(self):
        return self.book_instances.filter(status__exact='g').count()
    get_available_instances.short_description = _('prieinamu kopiju kiekis')


class Bookinstance(models.Model):
    id = models.UUIDField('id', primary_key=True, default=uuid.uuid4, help_text=_('unikalus ID knygos kopijai'), editable=False)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True, related_name='book_instances', verbose_name=_('knyga'))
    due_back = models.DateField(_('grazinama'), null=True, blank=True, db_index=True)

    LOAN_STATUS = (
        ('a', _('administruojama')),
        ('b', _('paimta')),
        ('g', _('galima paimti')),
        ('r', _('rezervuota')),      
    )

    status = models.CharField(verbose_name=_('statusas'), max_length=1, choices=LOAN_STATUS, blank=True, default='a', db_index=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='book_instances', verbose_name=_('skaitytojas'), null=True, blank=True)


    def __str__(self):
        return f'{str(self.id)} - {self.book.title}'

    @property
    def is_overdue(self):
        if self.due_back and self.due_back < date.today():
            return True
        return False 

    class Meta:
        ordering = ['due_back']
        verbose_name = _('knygos kopija')
        verbose_name_plural = _('knygu kopijos')


class BookReview(models.Model):
    book = models.ForeignKey(
        Book, 
        on_delete=models.CASCADE, 
        related_name='book_reviews', 
        verbose_name=_('knyga'),
        null=True,
        blank=True,
    )
    reviewer = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='book_reviews',
        verbose_name=_('skaitytojas'),
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    content = HTMLField(_('atsiliepimas'))

    def __str__(self):
        return f'{self.book} - {self.reviewer} - {self.created_at}'

library/books/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import BookReview
from django.conf import settings


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer')
        widgets = {
            'content': TinyMCE(mce_attrs=settings.TINYMCE_USER_CONFIG),
            'book': forms.HiddenInput(),
            'reviewer': forms.HiddenInput(),
        }

library/books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormMixin
from .forms import BookReviewForm
from .models import Book, Author, Bookinstance


# gali buti 2 view funkciniai ir ... 
# Funkcinis view
def index(request):
    num_books = Book.objects.all().count()
    num_instances = Bookinstance.objects.all().count()
    num_instances_available = Bookinstance.objects.filter(status__exact='g').count()
    num_authors = Author.objects.all().count()
    num_visits = request.session.get('num_visits', 1 )
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_authors': num_authors,
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_visits': num_visits,
    }
    return render(request, 'books/index.html', context)


# def search(request):
#     search = request.GET.get('search')
#     search_result = Book.objects.filter(

#     )
#     return render(request, 'books/search.html', {'books': search_result, 'search': search,})

def authors(request):
    paginator = Paginator(Author.objects.all(), 3)
    page_number = request.GET.get('page')
    authors = paginator.get_page(page_number)
    
    return render(request, 'books/authors.html', {'authors': authors})


def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'books/author.html', {'author': author})


# class based views
class BookListView(generic.ListView):
    model = Book
    context_object_name = 'books'
    # queryset = Book.objects.filter(title__icontains='')
    template_name = 'books/book_list.html'
    extra_context = {'spalva2': '#06f'}
    # paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request and self.request.GET and self.request.GET.get('search'):
            search = self.request.GET.get('search')
            queryset = queryset.filter(
                Q(title__icontains=search) |
                Q(summary__icontains=search) |
                Q(author__last_name__istartswith=search)
            )
        return queryset

    #  2 skirtingi aprasymo budai, rezultatas tas pats
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'spalva': '#fc0'})
        # context = {}
        # context.update({'books': self.get_queryset()})
        return context


class BookDetailView(generic.DetailView, FormMixin):
    model = Book
    template_name = 'books/book_detail.html'
    form_class = BookReviewForm

    def get_success_url(self):
        return reverse('book', kwargs={'pk': self.object.id })

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.book = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super().form_valid(form)


class LoanedBooksByUser(LoginRequiredMixin, generic.ListView):
    model = Bookinstance
    template_name = 'books/user_book_list.html'
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().filter(reader=self.request.user).filter(Q(status__exact='b') | Q(status__exact='r')).order_by('-due_back')

library/books/templates/books/author.html
{% extends 'books/base.html' %}
{% block content %}
    <div class= "container py-3">
        <h1>{{ author }}</h1>
            {% if author.description %}
                <p>{{ author.description|safe }}</p>
            {% endif %}
        <h2>Knygos</h2>
        <div class="list-group">
            {% for book in author.books.all %}
                <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="{% url 'book' book.id %}">
                    <span class="flex-grow-1"> {{ book.title }} </span>
                    <span class="badge badge-success badge-pill ml-1">kopiju: {{ book.get_available_instances }}</span>
                    <span class="badge badge-dark badge-pill ml-1">prieinamu: {{ book.book_instances.count }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}
{% block title %} {{ author }} | {{ block.super }} {% endblock title%}

library/books/templates/books/authors.html
{% extends 'books/base.html' %}
{% block content %}
    <div class= "container py-3">
        <h1>Autoriai</h1>

        {% include 'books/includes/paginator_for_authors.html' %}

        <div class="list-group">
        {% for author in authors %}
                <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="{% url 'author' author.id %}">
                {{ author }}
                <span class="badge badge-dark badge-pill">knygu: {{ author.get_books_count }}</span>
                </a>
        {% endfor %}
        </div>

        {% include 'books/includes/paginator_for_authors.html' %}
        
    </div>
{% endblock content %}

library/books/templates/books/base.html
<!DOCTYPE html>{% load static i18n %}{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Biblioteka{% endblock title %}</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">{% block navigation %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Pradzia</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'books' %}">Viso knygos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'authors' %}">Visi autoriai</a></li>
                        <li class="nav-item">
                            <form action="{% url 'books' %}" method="get" class="mb-3">
                                <input class="bg-dark text-light" type="text" name="search" placeholder="ieskoti knygos" value="{{ request.GET.search }}">
                                <button type="submit" class="btn btn-primary ml-1">&#128269;</button>
                            </form>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item"><a href="{% url 'view_profile' %}" class="nav-item">&#128100; {{ request.user.username }} </a></li>
                            {% if request.user.is_superuser or request.user.is_staff %}
                                <li class="nav-item"><a class="nav-item" href="{% url 'admin:index' %}">Administracija </a></li>
                            {% endif %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next=/library">&#128682;</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Prisijungti</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registruotis</a></li>
                        {% endif %}
                            <li class="nav-item">
                                <form action="{% url 'set_language'%}" method="post">
                                    {% csrf_token %}
                                    <input next="next" type="hidden" value="{{ redirect_to }}">
                                    <select class="form-control bg-dark text-light" name="language" onchange="this.form.submit()">
                                        {% get_available_languages as LANGUAGES %}
                                        {% for lang in LANGUAGES %}
                                        {{lang}}
                                            <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %}selected="selected"{% endif %}>
                                                {{ lang.0 }}: {{ lang.1 }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </form>
                            </li>
                    </ul>{% endblock navigation %}
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            {% block messages %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock content %}
            {% endblock messages %}
        </div>
    </main>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</body>
</html>

library/books/templates/books/book_detail.html
{% extends 'books/base.html' %}
{% load static %}
{% block content %}
    <div class="container py-3">
        <h1>{{ book.title }}</h1>
        <a href="{% url 'author' book.author.id %}"><h2>{{ book.author }}</h2></a>
        <div class="d-flex p-2 bg-light small">
            {% if book.genre.count > 0 %}
                <span class="flex-shrink-1">Žanrai:</span>
                {% for genre in book.genre.all %}
                    <span class="badge badge-pill badge-secondary ml-1">{{ genre }}</span>
                {% endfor %}
            {% else %}
                <span class="flex-shrink-1">Žanrų nerasta</span>
            {% endif %}
            <span class="flex-grow-1 ml-2">ISBN: {{ book.isbn }}</span>
        </div>
    {% if book.cover %}
        <img style="max-width: 400px;" class="img-fluid img-thumbnail float-right ml-3" src="{{ book.cover.url }}">
    {% else %}
        <img style="max-width: 400px;" class="img-fluid img-thumbnail float-right ml-3" src="{% static 'books/img/vibrant-abstract-book-cover.jpg' %}">
    {% endif %}
    <p>{{ book.summary|safe }}</p>
    <h3>Atsiliepimai</h3>
    {% if book.book_reviews.count > 0%}
        {% for review in book.book_reviews.all %}
        <div class="card">
            <div class="card-body">
                <span class="text-muted float-right">{{ review.created_at }}</span>
                <a href="{% url 'view_user_profile' review.reviewer.id %}">
                    {% if review.reviewer.user_profile.picture %}
                        <img class="img-fluid rounded-circle mr-2 float-left" style="max-width: 40px;" src="{{ review.reviewer.user_profile.picture.url }}">
                    {% else %}
                        <img class="img-fluid rounded-circle mr-2 float-left" style="max-width: 40px;" src="{% static 'user_profile/img/default.png' %}">
                    {% endif %}
                    <h5 class="card-title">{{ review.reviewer }}</h5>
                </a>
                {{ review.content|safe }}
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-secondary">Ši knyga kolkas atsiliepimų neturi</div>
    {% endif %}
    {% if user.is_authenticated %}
    <div class="FieldWrapper">
        <h4>Palikite Atsiliepimą</h4>
        <form method="post" action="">
            {% csrf_token%}
            {{ form.content }}<br/>
            <input type="submit" value="išsaugoti" class="btn btn-primary">
        </form>
    </div>
    {% endif %}
    <h3>Knygos kopijos bibliotekoje</h3>
    {% if book.book_instances.count > 0 %}
        <div class="list-group">
            {% for instance in book.book_instances.all %}
            <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <span class="flex-grow-1">{{ instance.id }}</span>
                <span class="badge 
                {% if instance.status == 'g' %}badge-success
                {% elif instance.status == 'a' %}badge-secondary
                {% elif instance.status == 'p' %}badge-danger
                {% else %}badge-warning{% endif %}
                badge-pill ml-1">{{ instance.get_status_display }}</span>
                {% if instance.status != 'g' %}
                <span class="ml-2">bus grąžinta: {{ instance.due_back }}</span>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-secondary">Bibliotekoje knygos kopijų kolkas nėra</div>
    {% endif %}
    </div>
{% endblock content %}
{% block title %}{{ book.title }} | {{ block.super }}{% endblock title %}

library/books/templates/books/book_list.html
{% extends 'books/base.html' %}
{% block content %}
    <div class= "container py-3">
        <h1>Knygos</h1>

        {% include 'books/includes/paginator.html' %}

        <div class="list-group">
        {% for book in books %}
                <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="{% url 'author' book.author.id %}">
                {{ book }}
                    <span class="flex-grow-1"> {{ book }} </span>
                    <span class="badge badge-success badge-pill ml-1">kopiju: {{ book.get_available_instances }}</span>
                    <span class="badge badge-dark badge-pill ml-1">prieinamu: {{ book.book_instances.count }}</span>
                </a>
                <div class="list-group-item small pt-1 bg-light">
                    {% if book.genre.count > 0 %}
                        <span class="flex-shrink-1">Zanrai:</span>
                        {% for genre in book.genre.all %}
                            <span class="badge badge-pill ml-1" style="background-color: {{ spalva }}">{{ genre }}</span>
                        {% endfor %}
                    {% else %}
                        <span class="flex-shrink-1">Zanru nerasta</span>
                    {% endif %}
                </div>
        {% endfor %}
        </div>

        {% include 'books/includes/paginator.html' %}

    </div>
{% endblock content %}

{% block title %} Knygos | {{ block.super }} {% endblock title%}

library/books/templates/books/index.html
{% extends 'books/base.html' %}
{% load i18n %}
{% block content %}
<div class="container"> {# komentaras kaip django tagas arba kintamasis#}
    <h1>{% trans 'Rajono Biblioteka' %}</h1>
    {% comment 'jeigu reikia kazka paslepti' %}sio teksto nerodys useriui{% endcomment%}
    <h4>{% trans 'Šiuo metu turime' %}</h4>
    <ul>
        <li>{% trans 'Knygu' %}: <strong>{{ num_books }}</strong> </li>
        <li>{% trans 'Kopiju' %}: <strong>{{ num_instances }}</strong> </li>
        <li>{% trans 'Prieinamu kopiju' %}: <strong>{{ num_instances_available }}</strong> </li>
        <li>{% trans 'Autoriu' %}: <strong>{{ num_authors }}</strong> </li>
        <li>{% trans 'Apsilankymu skaicius' %}: <strong>{{ num_visits }}</strong> </li>
    </ul>
</div>
{% endblock content %}

library/books/templates/books/user_book_list.html
{% extends 'books/base.html' %}
{% block content %}
    <div class= "container py-3">
        <h1>Mano paimtos knygos</h1>

        {% if bookinstance_list %}
        {% include 'books/includes/paginator.html' %}
        <div class="list-group">
            {% for copy in bookinstance_list%}
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="{% url 'book' copy.book.id %}">
                <span class="flex-grow-1"> {{ copy.book }} </span>
                <span class="badge {% if copy.is_overdue %}badge-danger{% else %} badge-dark {% endif %} badge-pill ml-1">grazinti reikia: {{ copy.due_back }}</span>
                <span class="badge badge-light badge-pill ml-1">{{ copy.get_status_display }}</span>
            </a>
            {% endfor %}
        </div>
        {% else %}
        <div class="list-group">
            Siuo mentu nepasiemete knygu
        </div>
        {% endif %}
    </div>
{% endblock content %}      
{% block title %} Mano knygos | {{ block.super }} {% endblock title%}